"""add brand_logo to cars

Revision ID: 47d8edb92a63
Revises: 1090e3417f09
Create Date: 2026-02-14 15:57:59.380506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d8edb92a63'
down_revision = '1090e3417f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_logo', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('brand_logo')

    # ### end Alembic commands ###
