"""Add price fields

Revision ID: 91751e59cce8
Revises: 47d8edb92a63
Create Date: 2026-02-15 21:27:02.929804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91751e59cce8'
down_revision = '47d8edb92a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('price_per_day')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
